# Jekyll Configuration File
# https://jekyllrb.com/
# https://mjskolne.github.io/SportOfLife
# 
---
layout: default
title: Sport of Life
description: A coaching philosophy, creative work in progress, a personal development guide, written as a we story and a gamification of life, to inspire, for and by Mitch Skolnekovich.
---


# https://pages.github.com/themes/
# GFM is GitHub Flavored Markdown
# theme: modernist
# permalink: pretty
markdown: kramdown

# Jekyll Exclude
exclude:
    - README.md
